#ifndef SIMPLE_GAME_LIBRARY_DEFINES
#define SIMPLE_GAME_LIBRARY_DEFINES

#define NUMBER_OF_IMAGES 1024
#define MAX_SFX 128
#define NUMBER_OF_FONTS 64

#define MAX_JOYSTICK 16
#define DEADZONE 4096

#define BACKGROUND_IMG 0
#define SPRITE_IMG 1
#define STATIC_IMG 2

#endif
